server:
  port: 8081

spring:
  application:
    name: logclient

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8080/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

